### ISSUE TITLE
Use just angular?

### ISSUE THREAD

**Issue by JohnnyTheTank** [picheli20/example-json-schema#1]
Is it possible to use this tool just with angular. So angular will get the json schema and creates the DOM by it self?

**Comment by picheli20** [comment]
The only dependency its the [ui-router](https://github.com/angular-ui/ui-router), the others framework its not necessary.

**Comment by JohnnyTheTank** [comment]
Well, I had something other in mind.

I thought about loading a json schema file with angular via $http and creating html with this schema on the fly. is this possible?

**Comment by picheli20** [comment]
Is this what im doing in angular-json-schema, but to make the renderization, I use the ui-router. But the request url is hardcoded until we decided the best way to make the requests. The url hard coded is `'/data/pageSchema.json'`

**Comment by JohnnyTheTank** [comment]
do you have access to gitter? could we talk in chat?

**Comment by picheli20** [comment]
I just added you, https://gitter.im/picheli20/angular-json-schema
